data:
  data_path: "Preprocessed/Data45"
  val_ratio: 0.2
  batch_size: 32

model:
  type: "attention_gru"
  input_size: 126
  hidden_size: 64
  bidirectional: true
  dropout: 0.5
  num_layers: 1

train:
  epochs: 200
  learning_rate: 0.001
  patience: 20

output:
  dir: "Output/Models/Attention_GRU"
  note: "Hand_Features"
